### PR TITLE
Milestone-3 Add style to the leaderboard

### PR DESCRIPTION
**Pull request by Jmagero**
In this milestone I achieved the following
- [x] Improved the look and feel of the application by adding the styles 
- [x] Kept the general layout of the wireframe
- [x] Used plain CSS

### CODE REVIEW

**Comment by Jmagero** [comment]
- [x] Add style

**Review by mimipeshy — CHANGES_REQUESTED** [review]
## Hi @Jmagero  👋🏾 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Kindly update your README file which contains all that's needed for running the app. You can use [this template](https://github.com/microverseinc/readme-template) and edit where necessary
- [ ] Kindly ensure your PR is professional with a brief description of what you have achieved

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

**Comment by Jmagero** [comment]
- [x] Add README

**Review by hemantso — CHANGES_REQUESTED** [review]
Hi @Jmagero, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Alt Text
 ## Required Changes ♻️

- [ ] As requested by the previous reviewer, kindly ensure your PR is professional with a brief description of what you have achieved. We can do this by editing the PR's description.

## Optional suggestions

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Jmagero** [comment]
@mimipeshy Please elaborate on this requirement:
Kindly ensure your PR is professional with a brief description of what you have achieved.
kindly if possible share a link to an example of what I should do.

Thank you

**Comment by Jmagero** [comment]
@hemant-soni-vst-au4 
Please elaborate on this requirement:
Kindly ensure your PR is professional with a brief description of what you have achieved.
kindly if possible share a link to an example of what I should do.

Thank you

**Comment by mimipeshy** [comment]
@Jmagero kindly edit this ⬇️ give a summary of what you did in this milestone 
image

**Comment by Jmagero** [comment]
@mimipeshy 
I added this description:
image
image

**Comment by Jmagero** [comment]
These are the requirements for this milestone. So basically what I did was to style
image

**Comment by mimipeshy** [comment]
@Jmagero it should be at the top description part. It's the first thing a user reads when they open your PR. It should have a short summary describing introduced changes in more detail.

**Comment by mimipeshy** [comment]
> These are the requirements for this milestone. So basically what I did was to style
> image

Then that is what you write in your PR-> For example  you can say 
```
In this milestone, i achieved the following

- Added styling to the app 
```
This way a user already knows what to expect from your PR. It's clear and precise 😄

**Comment by Jmagero** [comment]
@mimipeshy Thanks for the help

**Review by sinansevgi — APPROVED** [review]
# Approved :heavy_check_mark: 

Hi @Jmagero , 

Great work with making all the changes requested by the previous TSE. 
Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
